# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\SynologyDrive\repos\thylacine-BIThub\BIThub\Datapad\views\resources\mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_datapadMain(object):
    def setupUi(self, datapadMain):
        datapadMain.setObjectName("datapadMain")
        datapadMain.resize(1280, 692)
        self.centralwidget = QtWidgets.QWidget(datapadMain)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = dataVisual_Widget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = dbList_Widget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout.addWidget(self.widget_2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        datapadMain.setCentralWidget(self.centralwidget)

        self.retranslateUi(datapadMain)
        QtCore.QMetaObject.connectSlotsByName(datapadMain)

    def retranslateUi(self, datapadMain):
        _translate = QtCore.QCoreApplication.translate
        datapadMain.setWindowTitle(_translate("datapadMain", "Datapad"))
from views.widgetsCtrl import dataVisual_Widget, dbList_Widget
